<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit861b9579c9e0292155dfb983f2c3e029
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MistrFachman\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MistrFachman\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/App',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'MistrFachman\\MyCred\\ECommerce\\BalanceCalculator' => __DIR__ . '/../..' . '/src/App/MyCred/ECommerce/BalanceCalculator.php',
        'MistrFachman\\MyCred\\ECommerce\\CartContext' => __DIR__ . '/../..' . '/src/App/MyCred/ECommerce/CartContext.php',
        'MistrFachman\\MyCred\\ECommerce\\Manager' => __DIR__ . '/../..' . '/src/App/MyCred/ECommerce/Manager.php',
        'MistrFachman\\MyCred\\ECommerce\\Purchasability' => __DIR__ . '/../..' . '/src/App/MyCred/ECommerce/Purchasability.php',
        'MistrFachman\\MyCred\\ECommerce\\UiModifier' => __DIR__ . '/../..' . '/src/App/MyCred/ECommerce/UiModifier.php',
        'MistrFachman\\Services\\ProductService' => __DIR__ . '/../..' . '/src/App/Services/ProductService.php',
        'MistrFachman\\Shortcodes\\ProductGridShortcode' => __DIR__ . '/../..' . '/src/App/Shortcodes/ProductGridShortcode.php',
        'MistrFachman\\Shortcodes\\ShortcodeBase' => __DIR__ . '/../..' . '/src/App/Shortcodes/ShortcodeBase.php',
        'MistrFachman\\Shortcodes\\ShortcodeManager' => __DIR__ . '/../..' . '/src/App/Shortcodes/ShortcodeManager.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit861b9579c9e0292155dfb983f2c3e029::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit861b9579c9e0292155dfb983f2c3e029::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit861b9579c9e0292155dfb983f2c3e029::$classMap;

        }, null, ClassLoader::class);
    }
}
