<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'MistrFachman\\MyCred\\ECommerce\\BalanceCalculator' => $baseDir . '/src/App/MyCred/ECommerce/BalanceCalculator.php',
    'MistrFachman\\MyCred\\ECommerce\\CartContext' => $baseDir . '/src/App/MyCred/ECommerce/CartContext.php',
    'MistrFachman\\MyCred\\ECommerce\\Manager' => $baseDir . '/src/App/MyCred/ECommerce/Manager.php',
    'MistrFachman\\MyCred\\ECommerce\\Purchasability' => $baseDir . '/src/App/MyCred/ECommerce/Purchasability.php',
    'MistrFachman\\MyCred\\ECommerce\\UiModifier' => $baseDir . '/src/App/MyCred/ECommerce/UiModifier.php',
    'MistrFachman\\Shortcodes\\ProductGridShortcode' => $baseDir . '/src/App/Shortcodes/ProductGridShortcode.php',
    'MistrFachman\\Shortcodes\\ShortcodeBase' => $baseDir . '/src/App/Shortcodes/ShortcodeBase.php',
    'MistrFachman\\Shortcodes\\ShortcodeManager' => $baseDir . '/src/App/Shortcodes/ShortcodeManager.php',
);
